n1 = int(input('Digite um valor: '))
n2 = int(input('Digite outro valor: '))
print('A soma entre {} e {} é {}'.format(n1, n2, n1 + n2))
print('A subtração de {} por {} é igual a {}'.format(n1, n2, n1 - n2))
print('A multiplicação entre {} e {} é igual a {}'.format(n1, n2, n1 * n2))
print('A divisão de {} por {} é igual a {}'.format(n1, n2, n1 / n2))
print('A divisão inteira de {} por {} é igual a {}'.format(n1, n2, n1 // n2))
print('O resto da divisão de {} por {} é igual a {}'.format(n1, n2, n1 % n2))
print('A potencialização de {} elevado a {} é igual a {}'.format(n1, n2, n1 ** n2))
