a = 'Achei Deus em um tomate'
print(a[1:18:2])
print(len(a))
print(a.count('e'))
print(a.find('tomate'))
print('tomate' in a)
print(a.replace('tomate', 'mamão'))
print(a.upper())
print(a.lower())
b = '   Farofa de suco   '
print(b.capitalize())
print(b.title())
print(b.lstrip())
print(b.rstrip())
print(a.split(), b.split())
print(' '.join(a))