var = input('Digite algo: ')
print('O tipo primitivo dessa variável é', type(var))
print('Só tem espaços?', var.isspace())
print('É uma palavra?', var.isalpha())
print('É um número?', var.isnumeric())
print('É alfanumérico?', var.isalnum())
print('É somente em letras maiúsculas?', var.isupper())
print('É somente em letras minúsculas?', var.islower())
print('Está capitalizada?', var.istitle())
